#!/usr/bin/env python3
"""Generate one fence-aware Vale rule per required section.

Reads scripts/modes.yaml and writes styles/AgenticWriting/<rule>.yml. Run it after
editing the manifest; scripts/check-generated-rules.sh fails if the two disagree.

    python3 scripts/generate-mode-rules.py            # write
    python3 scripts/generate-mode-rules.py --check    # report drift, write nothing

The rules were `extends: occurrence` with a `(?m)` token and `scope: raw`. Raw text
does not distinguish a heading from a heading quoted inside a fenced code block, so a
document that only showed the required format satisfied the check. The generated rule
walks the document line by line, toggles a fence flag, and looks for the section only
outside a fence.
"""
import argparse
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / 'scripts' / 'modes.yaml'
OUT = ROOT / 'styles' / 'AgenticWriting'
BANNER = '# GENERATED by scripts/generate-mode-rules.py from scripts/modes.yaml. Do not edit.'

TEMPLATE = """{banner}
{comment}
extends: script
message: {message}
level: error
scope: raw
script: |
  text := import("text")
  matches := []
  in_fence := false
  found := false
  lines := text.split(scope, "\\n")

  for line in lines {{
    // A Tengo raw string is backtick-delimited, so a pattern holding a backtick
    // cannot be one literal. The runs are spliced back in as quoted strings.
    if text.re_match({fence}, line) {{
      in_fence = !in_fence
    }} else if !in_fence {{
      if text.re_match({pattern}, line) {{
        found = true
      }}
    }}
  }}

  // Report against the first line. Tengo's len() counts bytes, which is what Vale
  // wants for a span, and an empty first line still needs a non-zero one.
  if !found {{
    span := len(lines[0])
    if span == 0 {{ span = 1 }}
    matches = append(matches, {{begin: 0, end: span}})
  }}
"""

WHY_FENCE = (
    "This is a script rule rather than an occurrence count. It needs scope: raw to see\n"
    "document structure, and raw text does not distinguish a heading from a heading\n"
    "quoted inside a fenced code block. As an occurrence rule it counted the quoted one,\n"
    "so a document that merely showed the required format passed. The templates and\n"
    "docs/writing-modes.md both quote these headings, so this was not hypothetical.\n"
    "\n"
    "Presence only. Vale cannot judge whether the section says anything.\n"
    "\n"
    "Known error mode: any fence marker toggles the flag, so a ``` inside a ~~~ block\n"
    "closes it early and a heading after that point counts. An unclosed fence hides\n"
    "every heading below it, which makes the rule fire rather than go quiet."
)


def tengo_string(pattern):
    """Render a regex as a Tengo string expression.

    Tengo delimits a raw string with a backtick, so the fence pattern — which has to
    match ``` — cannot be a single literal. Splicing the backtick runs back in as
    quoted strings is what the two hand-written script rules already do.
    """
    out = []
    for seg in re.split(r'(`+)', pattern):
        if not seg:
            continue
        out.append(f'"{seg}"' if seg[0] == '`' else f'`{seg}`')
    return '+'.join(out)


def block(text):
    """Render a paragraph as a YAML comment block."""
    return '\n'.join(f'# {line}'.rstrip() for line in text.rstrip('\n').split('\n'))


def render(mode, section, fence):
    if 'inline' in section:
        pattern = f"(?i){section['inline']}"
    else:
        # CommonMark: an ATX heading takes at most three spaces of indentation.
        # Four or more make the line an indented code block, and `[ \t]*` counted
        # one of those as a real heading.
        pattern = rf"(?i)^[ ]{{0,3}}{section['levels']}[ \t]+{section['heading']}\b"

    parts = [section.get('cites') or mode.get('cites') or '', WHY_FENCE,
             mode.get('scope_note', '')]
    comment = '\n#\n'.join(block(p) for p in parts if p.strip())

    return TEMPLATE.format(
        banner=BANNER,
        comment=comment,
        message=yaml.safe_dump(section['message'], default_style='"',
                               width=10 ** 6).strip().rstrip('\n'),
        fence=tengo_string(fence),
        pattern=tengo_string(pattern),
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='report drift and exit non-zero; write nothing')
    args = ap.parse_args()

    manifest = yaml.safe_load(MANIFEST.read_text())
    fence = manifest['fence']
    drift, wrote = [], 0

    for mode in manifest['modes']:
        for section in mode['sections']:
            path = OUT / f"{section['rule']}.yml"
            want = render(mode, section, fence)
            have = path.read_text() if path.is_file() else None
            if have == want:
                continue
            if args.check:
                drift.append(f"{path.relative_to(ROOT)} "
                             f"{'differs from' if have else 'is missing, per'} the manifest")
            else:
                path.write_text(want)
                wrote += 1

    # A rule file that carries the banner but no longer appears in the manifest is
    # an orphan: nothing regenerates it and nothing would notice it going stale.
    named = {s['rule'] for m in manifest['modes'] for s in m['sections']}
    for path in sorted(OUT.glob('*.yml')):
        if path.stem not in named and path.read_text().startswith(BANNER):
            drift.append(f"{path.relative_to(ROOT)} is generated but the manifest "
                         f"no longer names it — delete the file or restore the entry")

    if args.check:
        for d in drift:
            print(f"FAIL {d}")
        if drift:
            print("\nRun: python3 scripts/generate-mode-rules.py")
            return 1
        print(f"All {len(named)} generated rules match scripts/modes.yaml.")
        return 0

    for d in drift:
        print(f"FAIL {d}")
    print(f"Wrote {wrote} of {len(named)} rules to {OUT.relative_to(ROOT)}/.")
    return 1 if drift else 0


if __name__ == '__main__':
    sys.exit(main())
